language: node_js
deploy:
  provider: heroku
  api_key:
    secure: qJAFsUp0uuRIzpTzZRAANjEweXPk5Lc2a8oo+UNugIFIUY4lssOwI9bWP/XZwlOn2/TzLANkoqk3HaPhtEccKBc6WdRe423EGD4qPgdNr/eumzYgRnnNpwWifTcLV42Sv86u0RIiEbdlgr3OEFJpufXkBGOMqgxzOI8mLmvJllCnNHLHxAUjGu8Nl1p5Z/RaxomXFtwszPEcQBZzFxfl6wmx+LLuyATbSXqM9igdh0ppXwy5ZJycRzj1hGvuW0ru+qKPXiPhTm4qx/bPy0edTlQonHVVzjsHLEtAzDg9SX+rfobsQrOUnbPApUqf0+567lUVFdgRJ93deuPnx2SWAy7pyT3fqFF9GLFUUbTrfCTPVf1uBUhIcXg8f38llwyD3tVDwOfvxtkjVda6hr6XCkc4lnh8FRuOfzvmYw6SsSffeDvcPIdbSTJvCFx5Lq0ce1IkwLnMhA/tV/xgvgGxTvcR+7W6/83rr1EXS2O9EvcmjKqIVkT2amXYmMabOg2qd085sSc0ZD+W/IV/k1t0DS0y/xccPiwzqFM1oGIcSNBsSC+7cGv71/fptOO2n4eqPlWABfNYEBfwaR0H+Fs2XwFBUEoc35JQzntqxifvr3B+N2/v134aWvhewcvS4CxFyEBW4NoGNVWD32ZpiYSNSy5rbAU8mvHJv30hXTSrPUc=
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t p3cycle:latest .

script:
  - docker run -v `pwd`/src:/code p3cycle:latest /bin/bash -c "cd /code && CI=true yarn test"

after_success:
  - docker build -t "$DOCKER_REGISTRY/$HEROKU_APP/web:latest" .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" "$DOCKER_REGISTRY"
  - docker push "$DOCKER_REGISTRY/$HEROKU_APP/web"