version: "3"

services:
 web:
  build:
   context: .
   dockerfile: Dockerfile.dev
  container_name: p3cycle-dev
  entrypoint: sh entrypoint.sh
  working_dir: /home/node
  ports:
   - 3000:3000
  volumes:
   - .:/home/node
