version: "3"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: p3cycle_dev
    entrypoint: sh entrypoint.sh
    working_dir: /home/node
    ports:
      - 3000:3000
    volumes:
      - .:/home/node
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p3cycle
    ports:
      - 5000:5000
